feature/new&modifies endpoints, changes in db
Rectle/rectle-service pull request #16
Opened 2023-08-06 18:14 UTC by PiotrKopecki

added 2 new columns:
description for project,
name for user

added/modified endpoints to:
- create project before uploading
- get all projects
- get project by id
- delete project by id with deleting files from storage, models&compilations&logs
- get user by email
- change user name

added/modifies some other things all according to this file: https://docs.google.com/document/d/1Zfj8pt8jx2SKvaBOP0pp8kQUpFm2Pqw5Ds53C4ga6X8/edit

2023-08-06 19:13 UTC, bartkalit requested changes

2023-08-06 19:13 UTC, bartkalit commented on src/main/resources/application.yml
> +      token: 7cdbc9084feb6ac0aa4c3d310416ec3b95de1aa8454cae6ca6f228c233a5582c
tego token'a to bym do .env przeniósł

2023-08-07 20:37 UTC, bartkalit approved these changes

2023-08-09 19:59 UTC, Michaqu11 approved these changes

2023-08-09 19:59 UTC, Michaqu11 commented on src/main/java/com/rectle/project/ProjectService.java
> +				.description(createProjectDto.getDescription())
dodaj tagi

2023-08-11 17:51 UTC, merged